#!/usr/bin/env node
/**
 * tou.gg brand assets — generated in code, never by an image model.
 *
 *   node scripts/brand.mjs [--out dir]
 *
 * Default `--out` is `public/`. The brand-asset pass stages under
 * `/workspace/.grok/brand-out` then hands files over with write-atomic.mjs
 * so a mid-build `vite` never copies a half-written JPEG.
 *
 * Writes:
 *   favicon.svg            geometric TOU monogram (16-unit, crisp at 16px)
 *   apple-touch-icon.svg   same mark, padded for the iOS rounded-square mask
 *   og.svg                 vector 1200×630 lockup
 *   og.png                 raster of the same lockup (Pillow)
 *   og.jpg                 1200×630 JPEG, ffmpeg -q:v 4
 *
 * Raster text uses TTFs in `.grok/fonts/` (Instrument Serif, IBM Plex Sans,
 * IBM Plex Mono). If those are missing it falls back to Liberation on disk —
 * it will not invent a font name that is not installed.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const PALETTE = {
  bg: "#0A0E1A",
  surface: "#101624",
  text: "#E6EDF3",
  mute: "#8B949E",
  accent: "#FF6B35",
  spark: "#FFB347",
  ai: "#00D4FF",
  ok: "#00FF88",
};

const OG = {
  width: 1200,
  height: 630,
  touSize: 400,
  touTracking: 10,
  touCyRatio: 0.455,
  ruleWidth: 120,
  ruleHeight: 4,
  ruleGap: 28,
  subSize: 40,
  subGap: 28,
  domainSize: 22,
  margin: 72,
};

function parseArgs(argv) {
  let out = join(ROOT, "public");
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--out") {
      const value = argv[++i];
      if (!value) throw new Error("--out needs a directory");
      out = resolve(ROOT, value);
    } else {
      throw new Error(`unexpected argument: ${argv[i]}`);
    }
  }
  return { out };
}

/** Shared TOU geometry on a 16×16 grid. Min feature = 1 unit → 1px at 16px. */
function monogramMarks() {
  const { text, accent, ok } = PALETTE;
  return [
    `<!-- t -->`,
    `<rect x="2" y="7" width="6" height="2" fill="${text}"/>`,
    `<rect x="4" y="7" width="2" height="18" fill="${text}"/>`,
    `<!-- o -->`,
    `<path fill="${text}" fill-rule="evenodd" d="M11 7h8v18h-8zm2 3h4v12h-4z"/>`,
    `<!-- u, bowl holds a 2px 'to you' spark -->`,
    `<rect x="21" y="7" width="2" height="14" fill="${text}"/>`,
    `<rect x="27" y="7" width="2" height="14" fill="${text}"/>`,
    `<rect x="21" y="19" width="8" height="2" fill="${text}"/>`,
    `<rect x="24" y="13" width="2" height="2" fill="${accent}"/>`,
    `<!-- > -->`,
    `<path d="M32 10l6 8-6 8" fill="none" stroke="${ok}" stroke-width="2" stroke-linecap="square"/>`,
  ].join("\n  ");
}

function faviconSvg() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 40 32">
  <title>tou></title>
  <rect width="40" height="32" fill="${PALETTE.bg}"/>
  ${monogramMarks()}
</svg>
`;
}

function appleTouchSvg() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48">
  <title>tou></title>
  <rect width="48" height="48" fill="${PALETTE.bg}"/>
  <g transform="translate(4 8)">
  ${monogramMarks()}
  </g>
</svg>
`;
}

function ogSvg() {
  const { width: w, height: h } = OG;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">
  <title>tou.gg — from me, to you</title>
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="0">
      <stop offset="0%" stop-color="${PALETTE.accent}"/>
      <stop offset="100%" stop-color="${PALETTE.spark}"/>
    </linearGradient>
  </defs>
  <rect width="${w}" height="${h}" fill="${PALETTE.bg}"/>
  <path d="M48 80 C 80 220, 40 360, 64 540" fill="none" stroke="${PALETTE.accent}" stroke-width="2"/>
  <path d="M1152 90 h-80 m80 28 h-48 m48 28 h-72 m72 28 h-40" fill="none" stroke="${PALETTE.ai}" stroke-width="1.5"/>
  <text x="${w / 2}" y="300" text-anchor="middle" font-family="IBM Plex Mono, Liberation Mono, monospace" font-size="140" font-weight="700" fill="url(#g)">tou></text>
  <text x="${w / 2}" y="390" text-anchor="middle" font-family="IBM Plex Mono, Liberation Mono, monospace" font-size="32" fill="${PALETTE.ai}">to you → tou.gg</text>
  <text x="${w / 2}" y="560" text-anchor="middle" font-family="IBM Plex Mono, Liberation Mono, monospace" font-size="22" fill="${PALETTE.mute}">15 products · 189 repos · 19 months solo</text>
</svg>
`;
}

const RASTER_PY = `# Regenerated by scripts/brand.mjs — do not edit by hand.
from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
BG, TEXT, MUTE, ACCENT, AI = "#0A0E1A", "#E6EDF3", "#8B949E", "#FF6B35", "#00D4FF"
TOU_SIZE = 400
TOU_TRACKING = 10
TOU_CY_RATIO = 0.455
RULE_W, RULE_H, RULE_GAP = 120, 4, 28
SUB_SIZE, SUB_GAP = 40, 28
DOMAIN_SIZE = 22
MARGIN = 72
SCALE = 2


def first_existing(paths):
    for p in paths:
        if p and os.path.isfile(p):
            return p
    raise FileNotFoundError("no TTF found among: " + ", ".join(paths))


def load_fonts(font_dir):
    display_path = first_existing(
        [
            str(font_dir / "InstrumentSerif-Regular.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        ]
    )
    italic_path = first_existing(
        [
            str(font_dir / "InstrumentSerif-Italic.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        ]
    )
    mono_path = first_existing(
        [
            str(font_dir / "IBMPlexMono-Regular.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        ]
    )
    display = ImageFont.truetype(mono_path, 168 * SCALE)
    italic = ImageFont.truetype(mono_path, 28 * SCALE)
    mono = ImageFont.truetype(mono_path, 22 * SCALE)
    print("fonts:", display.getname(), italic.getname(), mono.getname(), flush=True)
    return display, italic, mono, mono_path


def draw_tracked(draw, text, center, font, fill, tracking):
    lengths = [font.getlength(ch) for ch in text]
    total = sum(lengths) + tracking * (len(text) - 1)
    x = center[0] - total / 2
    y = center[1]
    for ch, ln in zip(text, lengths):
        draw.text((x, y), ch, font=font, fill=fill, anchor="lm")
        x += ln + tracking
    return total


def render(out_png, font_dir):
    display, italic, mono, mono_path = load_fonts(font_dir)
    img = Image.new("RGB", (W * SCALE, H * SCALE), BG)
    draw = ImageDraw.Draw(img)
    cx = W * SCALE / 2
    tou_y = H * SCALE * TOU_CY_RATIO
    tracking = TOU_TRACKING * SCALE
    draw_tracked(draw, "tou>", (cx, tou_y), display, ACCENT, tracking * 0.2)

    # Visual bottom of the (untracked) mm box sits very close to the tracked
    # drawing; use it for the rule so the lockup spacing stays stable.
    bb = draw.textbbox((cx, tou_y), "tou>", font=display, anchor="mm")

    # Visual bottom of the (untracked) mm box sits very close to the tracked
    # drawing; use it for the rule so the lockup spacing stays stable.
    bb = draw.textbbox((cx, tou_y), "TOU", font=display, anchor="mm")
    rule_w = RULE_W * SCALE
    rule_h = RULE_H * SCALE
    rule_y = bb[3] + RULE_GAP * SCALE
    draw.rectangle(
        [cx - rule_w / 2, rule_y, cx + rule_w / 2, rule_y + rule_h],
        fill=ACCENT,
    )
    sub_y = rule_y + rule_h + SUB_GAP * SCALE
    draw.text((cx, sub_y), "to you → tou.gg", font=italic, fill=AI, anchor="mt")
    margin = MARGIN * SCALE
    draw.text((cx, H * SCALE - margin), "15 products · 189 repos · 19 months solo", font=mono, fill=MUTE, anchor="md")

    tou_bb = draw.textbbox((cx, tou_y), "tou>", font=display, anchor="mm")
    sub_bb = draw.textbbox((cx, sub_y), "to you → tou.gg", font=italic, anchor="mt")
    dom_bb = draw.textbbox((cx, H * SCALE - margin), "15 products · 189 repos · 19 months solo", font=mono, anchor="md")
    print(
        "bbox TOU",
        tuple(round(v / SCALE, 1) for v in tou_bb),
        "sub",
        tuple(round(v / SCALE, 1) for v in sub_bb),
        "domain",
        tuple(round(v / SCALE, 1) for v in dom_bb),
        flush=True,
    )
    # Tracked TOU is slightly wider than the mm bbox — pad the crop gate.
    tracked_half = (
        (sum(display.getlength(ch) for ch in "tou>") + tracking * 0.2 * 3) / 2 / SCALE
    )
    extra_boxes = [("tou-tracked", (W / 2 - tracked_half, tou_bb[1] / SCALE, W / 2 + tracked_half, tou_bb[3] / SCALE))]
    for name, box in [("tou>", tou_bb), ("to you", sub_bb), ("stats", dom_bb)]:
        l, t, r, b = (v / SCALE for v in box)
        extra_boxes.append((name, (l, t, r, b)))
    for name, (l, t, r, b) in extra_boxes:
        if l <= 8 or t <= 8 or r >= W - 8 or b >= H - 8:
            raise SystemExit("crop gate: %s too close to edge %s" % (name, (l, t, r, b)))

    out = img.resize((W, H), Image.Resampling.LANCZOS)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    out.save(out_png, format="PNG", optimize=True)
    print("wrote", out_png, out.size, flush=True)

    # Square icons
    mono_icon = ImageFont.truetype(mono_path, 14)
    for size, name in [(32, "icon-32.png"), (180, "apple-touch-icon.png"), (192, "icon-192.png"), (512, "icon-512.png")]:
        im = Image.new("RGB", (size, size), BG)
        d = ImageDraw.Draw(im)
        f = ImageFont.truetype(mono_path, max(12, int(size * 0.34)))
        d.text((size / 2, size / 2), "tou>", font=f, fill=ACCENT, anchor="mm")
        dest = out_png.parent / name
        im.save(dest, format="PNG", optimize=True)
        print("wrote", dest, im.size, flush=True)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: brand-raster.py <out-png> <font-dir>")
    render(Path(sys.argv[1]), Path(sys.argv[2]))
`;

function run(cmd, args) {
  const result = spawnSync(cmd, args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) {
    throw new Error(`${cmd} ${args.join(" ")} exited ${result.status}`);
  }
  return result;
}

function main() {
  const { out } = parseArgs(process.argv.slice(2));
  mkdirSync(out, { recursive: true });

  writeFileSync(join(out, "favicon.svg"), faviconSvg());
  writeFileSync(join(out, "apple-touch-icon.svg"), appleTouchSvg());
  writeFileSync(join(out, "og.svg"), ogSvg());

  const fontDir = join(ROOT, ".grok/fonts");
  const rasterPy = join(ROOT, ".grok/brand-raster.py");
  writeFileSync(rasterPy, RASTER_PY);

  const pngPath = join(out, "og.png");
  run("python3", [rasterPy, pngPath, fontDir]);

  const jpgPath = join(out, "og.jpg");
  run("ffmpeg", [
    "-y",
    "-hide_banner",
    "-loglevel",
    "error",
    "-i",
    pngPath,
    "-vf",
    "scale=1200:630:force_original_aspect_ratio=increase,crop=1200:630",
    "-frames:v",
    "1",
    "-q:v",
    "4",
    "-pix_fmt",
    "yuvj444p",
    jpgPath,
  ]);

  console.log(`brand: wrote favicon.svg apple-touch-icon.svg og.svg og.png og.jpg → ${out}`);
}

try {
  main();
} catch (err) {
  console.error(`brand: ${err.message || err}`);
  process.exit(1);
}
