#!/usr/bin/env node
/**
 * tou.gg brand assets — generated in code, never by an image model.
 *
 *   node scripts/brand.mjs [--out dir]
 *
 * Default `--out` is `public/`. The brand-asset pass stages under
 * `/workspace/.grok/brand-out` then hands files over with write-atomic.mjs
 * so a mid-build `vite` never copies a half-written JPEG.
 *
 * Writes:
 *   favicon.svg            geometric TOU monogram (16-unit, crisp at 16px)
 *   apple-touch-icon.svg   same mark, padded for the iOS rounded-square mask
 *   og.svg                 vector 1200×630 lockup
 *   og.png                 raster of the same lockup (Pillow)
 *   og.jpg                 1200×630 JPEG, ffmpeg -q:v 4
 *
 * Raster text uses TTFs in `.grok/fonts/` (Instrument Serif, IBM Plex Sans,
 * IBM Plex Mono). If those are missing it falls back to Liberation on disk —
 * it will not invent a font name that is not installed.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

const PALETTE = {
  bg: "#0D1117",
  surface: "#161B22",
  text: "#E6EDF3",
  mute: "#8B949E",
  accent: "#FF6B35",
};

const OG = {
  width: 1200,
  height: 630,
  touSize: 400,
  touTracking: 10,
  touCyRatio: 0.455,
  ruleWidth: 120,
  ruleHeight: 4,
  ruleGap: 28,
  subSize: 40,
  subGap: 28,
  domainSize: 22,
  margin: 72,
};

function parseArgs(argv) {
  let out = join(ROOT, "public");
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === "--out") {
      const value = argv[++i];
      if (!value) throw new Error("--out needs a directory");
      out = resolve(ROOT, value);
    } else {
      throw new Error(`unexpected argument: ${argv[i]}`);
    }
  }
  return { out };
}

/** Shared TOU geometry on a 16×16 grid. Min feature = 1 unit → 1px at 16px. */
function monogramMarks() {
  const { text, accent } = PALETTE;
  return [
    `<!-- T -->`,
    `<rect x="1" y="3" width="4" height="2" fill="${text}"/>`,
    `<rect x="2" y="3" width="2" height="9" fill="${text}"/>`,
    `<!-- O: square ring, geometric cut -->`,
    `<path fill="${text}" fill-rule="evenodd" d="M6 3h4v9H6zm1 2h2v5H7z"/>`,
    `<!-- U -->`,
    `<rect x="11" y="3" width="2" height="7" fill="${text}"/>`,
    `<rect x="13" y="3" width="2" height="7" fill="${text}"/>`,
    `<rect x="11" y="10" width="4" height="2" fill="${text}"/>`,
    `<!-- .gg square seal -->`,
    `<rect x="13" y="13" width="2" height="2" fill="${accent}"/>`,
  ].join("\n  ");
}

function faviconSvg() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" shape-rendering="crispEdges">
  <title>TOU</title>
  <rect width="16" height="16" fill="${PALETTE.bg}"/>
  ${monogramMarks()}
</svg>
`;
}

function appleTouchSvg() {
  // 4 units of padding on a 24-unit canvas (~17%) keeps the mark inside the
  // iOS rounded-square mask (safe zone ≈ 80% / 10% inset each side).
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
  <title>TOU</title>
  <rect width="24" height="24" fill="${PALETTE.bg}"/>
  <g transform="translate(4 4)">
  ${monogramMarks()}
  </g>
</svg>
`;
}

function ogSvg() {
  const { width: w, height: h } = OG;
  const cx = w / 2;
  const touY = Math.round(h * OG.touCyRatio);
  const ruleY = 454;
  const subY = ruleY + OG.ruleHeight + OG.subGap;
  const ruleX = cx - OG.ruleWidth / 2;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">
  <title>tou.gg — Shipped to you.</title>
  <rect width="${w}" height="${h}" fill="${PALETTE.bg}"/>
  <text
    x="${cx}" y="${touY}"
    text-anchor="middle" dominant-baseline="middle"
    font-family="Instrument Serif, Liberation Serif, Georgia, serif"
    font-size="${OG.touSize}" font-weight="400"
    letter-spacing="${OG.touTracking}"
    fill="${PALETTE.text}"
  >TOU</text>
  <rect x="${ruleX}" y="${ruleY}" width="${OG.ruleWidth}" height="${OG.ruleHeight}" fill="${PALETTE.accent}"/>
  <text
    x="${cx}" y="${subY}"
    text-anchor="middle" dominant-baseline="hanging"
    font-family="Instrument Serif, Liberation Serif, Georgia, serif"
    font-style="italic" font-size="${OG.subSize}"
    fill="${PALETTE.mute}"
  >to you</text>
  <text
    x="${OG.margin}" y="${h - OG.margin}"
    text-anchor="start" dominant-baseline="auto"
    font-family="IBM Plex Mono, Liberation Mono, ui-monospace, monospace"
    font-size="${OG.domainSize}"
    fill="${PALETTE.mute}"
  >tou.gg</text>
</svg>
`;
}

const RASTER_PY = `# Regenerated by scripts/brand.mjs — do not edit by hand.
from __future__ import annotations

import os
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
BG, TEXT, MUTE, ACCENT = "#0D1117", "#E6EDF3", "#8B949E", "#FF6B35"
TOU_SIZE = 400
TOU_TRACKING = 10
TOU_CY_RATIO = 0.455
RULE_W, RULE_H, RULE_GAP = 120, 4, 28
SUB_SIZE, SUB_GAP = 40, 28
DOMAIN_SIZE = 22
MARGIN = 72
SCALE = 2


def first_existing(paths):
    for p in paths:
        if p and os.path.isfile(p):
            return p
    raise FileNotFoundError("no TTF found among: " + ", ".join(paths))


def load_fonts(font_dir):
    display_path = first_existing(
        [
            str(font_dir / "InstrumentSerif-Regular.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        ]
    )
    italic_path = first_existing(
        [
            str(font_dir / "InstrumentSerif-Italic.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
        ]
    )
    mono_path = first_existing(
        [
            str(font_dir / "IBMPlexMono-Regular.ttf"),
            "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        ]
    )
    display = ImageFont.truetype(display_path, TOU_SIZE * SCALE)
    italic = ImageFont.truetype(italic_path, SUB_SIZE * SCALE)
    mono = ImageFont.truetype(mono_path, DOMAIN_SIZE * SCALE)
    print("fonts:", display.getname(), italic.getname(), mono.getname(), flush=True)
    return display, italic, mono


def draw_tracked(draw, text, center, font, fill, tracking):
    lengths = [font.getlength(ch) for ch in text]
    total = sum(lengths) + tracking * (len(text) - 1)
    x = center[0] - total / 2
    y = center[1]
    for ch, ln in zip(text, lengths):
        draw.text((x, y), ch, font=font, fill=fill, anchor="lm")
        x += ln + tracking
    return total


def render(out_png, font_dir):
    display, italic, mono = load_fonts(font_dir)
    img = Image.new("RGB", (W * SCALE, H * SCALE), BG)
    draw = ImageDraw.Draw(img)
    cx = W * SCALE / 2
    tou_y = H * SCALE * TOU_CY_RATIO
    tracking = TOU_TRACKING * SCALE
    draw_tracked(draw, "TOU", (cx, tou_y), display, TEXT, tracking)

    # Visual bottom of the (untracked) mm box sits very close to the tracked
    # drawing; use it for the rule so the lockup spacing stays stable.
    bb = draw.textbbox((cx, tou_y), "TOU", font=display, anchor="mm")
    rule_w = RULE_W * SCALE
    rule_h = RULE_H * SCALE
    rule_y = bb[3] + RULE_GAP * SCALE
    draw.rectangle(
        [cx - rule_w / 2, rule_y, cx + rule_w / 2, rule_y + rule_h],
        fill=ACCENT,
    )
    sub_y = rule_y + rule_h + SUB_GAP * SCALE
    draw.text((cx, sub_y), "to you", font=italic, fill=MUTE, anchor="mt")
    margin = MARGIN * SCALE
    draw.text((margin, H * SCALE - margin), "tou.gg", font=mono, fill=MUTE, anchor="ld")

    tou_bb = draw.textbbox((cx, tou_y), "TOU", font=display, anchor="mm")
    sub_bb = draw.textbbox((cx, sub_y), "to you", font=italic, anchor="mt")
    dom_bb = draw.textbbox((margin, H * SCALE - margin), "tou.gg", font=mono, anchor="ld")
    print(
        "bbox TOU",
        tuple(round(v / SCALE, 1) for v in tou_bb),
        "sub",
        tuple(round(v / SCALE, 1) for v in sub_bb),
        "domain",
        tuple(round(v / SCALE, 1) for v in dom_bb),
        flush=True,
    )
    # Tracked TOU is slightly wider than the mm bbox — pad the crop gate.
    tracked_half = (
        (sum(display.getlength(ch) for ch in "TOU") + tracking * 2) / 2 / SCALE
    )
    extra_boxes = [("TOU-tracked", (W / 2 - tracked_half, tou_bb[1] / SCALE, W / 2 + tracked_half, tou_bb[3] / SCALE))]
    for name, box in [("TOU", tou_bb), ("to you", sub_bb), ("tou.gg", dom_bb)]:
        l, t, r, b = (v / SCALE for v in box)
        extra_boxes.append((name, (l, t, r, b)))
    for name, (l, t, r, b) in extra_boxes:
        if l <= 8 or t <= 8 or r >= W - 8 or b >= H - 8:
            raise SystemExit("crop gate: %s too close to edge %s" % (name, (l, t, r, b)))

    out = img.resize((W, H), Image.Resampling.LANCZOS)
    out_png.parent.mkdir(parents=True, exist_ok=True)
    out.save(out_png, format="PNG", optimize=True)
    print("wrote", out_png, out.size, flush=True)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("usage: brand-raster.py <out-png> <font-dir>")
    render(Path(sys.argv[1]), Path(sys.argv[2]))
`;

function run(cmd, args) {
  const result = spawnSync(cmd, args, {
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
  if (result.stdout) process.stdout.write(result.stdout);
  if (result.stderr) process.stderr.write(result.stderr);
  if (result.status !== 0) {
    throw new Error(`${cmd} ${args.join(" ")} exited ${result.status}`);
  }
  return result;
}

function main() {
  const { out } = parseArgs(process.argv.slice(2));
  mkdirSync(out, { recursive: true });

  writeFileSync(join(out, "favicon.svg"), faviconSvg());
  writeFileSync(join(out, "apple-touch-icon.svg"), appleTouchSvg());
  writeFileSync(join(out, "og.svg"), ogSvg());

  const fontDir = join(ROOT, ".grok/fonts");
  const rasterPy = join(ROOT, ".grok/brand-raster.py");
  writeFileSync(rasterPy, RASTER_PY);

  const pngPath = join(out, "og.png");
  run("python3", [rasterPy, pngPath, fontDir]);

  const jpgPath = join(out, "og.jpg");
  run("ffmpeg", [
    "-y",
    "-hide_banner",
    "-loglevel",
    "error",
    "-i",
    pngPath,
    "-vf",
    "scale=1200:630:force_original_aspect_ratio=increase,crop=1200:630",
    "-frames:v",
    "1",
    "-q:v",
    "4",
    "-pix_fmt",
    "yuvj444p",
    jpgPath,
  ]);

  console.log(`brand: wrote favicon.svg apple-touch-icon.svg og.svg og.png og.jpg → ${out}`);
}

try {
  main();
} catch (err) {
  console.error(`brand: ${err.message || err}`);
  process.exit(1);
}
