/**
 * tou.gg content model.
 *
 * Every string a visitor can read lives here, in three languages.
 * Pages are generated from this file by build.mjs — there is no second copy
 * of the copy anywhere in the repo.
 *
 * Numbers in `stats` and `products[].metric` were counted, not estimated.
 * See NOTES.md for how each one was verified and how to re-verify it.
 */

export const LOCALES = ["en", "uz", "ru", "zh"];
export const DEFAULT_LOCALE = "en";

export const site = {
  origin: "https://tou.gg",
  domain: "tou.gg",
  repo: "https://github.com/maqsudjon-cell/tou",
  name: "Maqsudjon Polatov",
  handle: "@toudotgg",
  role: { en: "Product engineer", uz: "Mahsulot muhandisi", ru: "Продуктовый инженер", zh: "产品工程师" },
  city: { en: "Tashkent", uz: "Toshkent", ru: "Ташкент", zh: "塔什干" },
  email: "polatovmaqsudjon1@gmail.com",
  tel: "+998959059493",
  telDisplay: "+998 95 905 94 93",
  telegram: "https://t.me/toudotgg",
  x: "https://x.com/toudotgg",
  instagram: "https://instagram.com/toudotgg",
  github: "https://github.com/maqsudjon-cell",
  huggingface: "https://huggingface.co/Maqsudjonpolatov",
  dataset: "https://huggingface.co/datasets/Maqsudjonpolatov/uz-lexicon-skeleton",
  lab: "https://maqsudjon.com",
  goatcounter: "https://tou.goatcounter.com/count",
  stats_url: "https://tou.goatcounter.com",
  // Search Console, URL-prefix property https://tou.gg/, HTML-tag method.
  // Do not remove this once verified — Google re-checks it.
  googleSiteVerification: "On9oW2bT9G3wndosR-K_KcL85-D6v_XpetjXbPEVUaY",
  updated: "2026-09-20",
  // Bump with scripts/brand.py OG_VERSION when the share card changes.
  ogImage: "/og-2026-09.jpg",
  // Regenerated by scripts/cv-pdf.mjs from the /cv/ page itself, one per
  // language tree. English keeps the bare name — it is the one HR gets.
  cvPdf: {
    en: "/Maqsudjon-Polatov-CV.pdf", uz: "/Maqsudjon-Polatov-CV-uz.pdf",
    ru: "/Maqsudjon-Polatov-CV-ru.pdf", zh: "/Maqsudjon-Polatov-CV-zh.pdf",
  },
};

/* Verified 2026-09-20. Re-verify: see NOTES.md §Numbers. */
export const stats = [
  { n: 15, label: { en: "live sites", uz: "ishlayotgan sayt", ru: "живых сайтов", zh: "个在线站点" } },
  { n: 191, label: { en: "public repos", uz: "ochiq repozitoriy", ru: "публичных репозиториев", zh: "个公开仓库" } },
  { n: 3000, plus: true, label: { en: "commits", uz: "kommit", ru: "коммитов", zh: "次提交" } },
  { n: 144, label: { en: "IELTS tests live", uz: "jonli IELTS testi", ru: "тестов IELTS в проде", zh: "套 IELTS 试题在线" } },
  { n: 19, label: { en: "months solo", uz: "oy yakka o‘zim", ru: "месяцев соло", zh: "个月独立开发" } },
];

export const tags = {
  education: { en: "Education", uz: "Ta’lim", ru: "Образование", zh: "教育" },
  ai: { en: "AI & language", uz: "AI va til", ru: "AI и язык", zh: "AI 与语言" },
  tools: { en: "Tools", uz: "Vositalar", ru: "Инструменты", zh: "工具" },
  music: { en: "Music", uz: "Musiqa", ru: "Музыка", zh: "音乐" },
  steel: { en: "Code & steel", uz: "Kod va temir", ru: "Код и сталь", zh: "代码与钢铁" },
  client: { en: "Client work", uz: "Buyurtma ish", ru: "Клиентские", zh: "客户项目" },
  studio: { en: "Studio", uz: "Studiya", ru: "Студия", zh: "工作室" },
  lab: { en: "Lab", uz: "Laboratoriya", ru: "Лаборатория", zh: "实验室" },
};

/**
 * Live sites. Order = the order they are shown.
 * `case: true` means a case study page is generated at /work/<slug>/.
 */
export const products = [
  {
    slug: "flarestamina",
    name: "FlareStamina",
    domain: "flarestamina.com",
    url: "https://flarestamina.com",
    tag: "education",
    hue: "#ff6b35",
    flagship: true,
    case: true,
    metric: { n: "144", label: { en: "tests live", uz: "test jonli", ru: "тестов в проде", zh: "套试题在线" } },
    dek: {
      en: "Free IELTS Academic platform. 144 timed mocks, AI writing feedback, a speaking lab. Teachers run it with a class.",
      uz: "Bepul IELTS Academic platformasi. 144 ta vaqtli mock, AI yozma tahlili, speaking laboratoriyasi. O‘qituvchilar sinf bilan ishlatadi.",
      ru: "Бесплатная платформа IELTS Academic. 144 теста на время, AI-разбор письма, speaking-лаб. Преподаватели ведут по ней группы.",
      zh: "免费的 IELTS Academic 平台。144 套限时模考、AI 写作评分、口语实验室。老师可以带着整个班级用。"
    },
    stack: ["Firebase", "Supabase", "PWA", "Claude API"],
    story: {
      problem: {
        en: "IELTS prep in Uzbekistan is paywalled, fragmented, and often a PDF dump. Teachers needed something they could actually run with a class. Students needed something they could open on a phone.",
        uz: "O‘zbekistonda IELTSga tayyorgarlik pullik, tarqoq, ko‘pincha shunchaki PDF uyumi. O‘qituvchiga sinfda ishlata oladigan narsa kerak edi. Talabaga telefonda ochiladigan narsa.",
        ru: "Подготовка к IELTS в Узбекистане — платная, разрозненная, часто просто свалка PDF. Преподавателю нужно было то, что можно вести с группой. Студенту — то, что открывается на телефоне.",
        zh: "乌兹别克斯坦的 IELTS 备考要么收费、要么零散，常常只是一堆 PDF。老师需要一个能真正带班用的东西，学生需要一个能在手机上打开的东西。"
      },
      constraint: {
        en: "Solo. Welding days, Tashkent evenings. No content team. If a feature needed a babysitter, it would die the week I went back to the shop.",
        uz: "Yakka o‘zim. Kunduzi payvand, kechqurun Toshkent. Kontent jamoasi yo‘q. Agar funksiya doim qarovga muhtoj bo‘lsa, ustaxonaga qaytgan haftamda o‘lardi.",
        ru: "Один. Днём сварка, вечером Ташкент. Никакой контент-команды. Если фича требует няньки — она умрёт на той неделе, когда я вернусь в цех.",
        zh: "一个人。白天焊接，晚上在塔什干。没有内容团队。哪个功能需要有人天天看着，我回车间的那一周它就死了。"
      },
      shipped: {
        en: "144 tests in production and 10 tools. AI essay feedback. A speaking lab. A 40-day tracker. PWA. The login walls came down — most of it is free, because a wall in front of a practice test is just another fee.",
        uz: "Prodda 144 ta test va 10 ta vosita. AI esse tahlili. Speaking laboratoriyasi. 40 kunlik tracker. PWA. Login devorlari olib tashlandi — ko‘p qismi bepul, chunki mashq testi oldidagi devor ham bir turdagi to‘lov.",
        ru: "144 теста в проде и 10 инструментов. AI-фидбэк по эссе. Speaking-лаб. 40-дневный трекер. PWA. Стены логина убраны — почти всё бесплатно: стена перед пробным тестом это та же плата.",
        zh: "生产环境里 144 套试题和 10 个工具。AI 作文反馈。口语实验室。40 天打卡。PWA。登录墙拆掉了 —— 大部分内容免费，因为在一套练习题前面立一道墙，不过是换个名目收费。"
      },
      hard: {
        en: "Scoring and content quality at volume, without a newsroom or a publishing house behind it. pangea8 is the rebrand case: the product outgrew the name.",
        uz: "Katta hajmda baholash va kontent sifati — orqada na tahririyat, na nashriyot bor. pangea8 — rebrending misoli: mahsulot nomdan o‘sib chiqdi.",
        ru: "Оценка и качество контента на объёме, без редакции и издательства за спиной. pangea8 — кейс ребрендинга: продукт перерос имя.",
        zh: "在这个量级上保证评分和内容质量，背后既没有编辑部，也没有出版社。pangea8 就是那个改名的案例：产品长大了，名字装不下了。"
      },
    },
  },
  {
    slug: "ailenta",
    name: "AI Lenta",
    domain: "ailenta.uz",
    url: "https://ailenta.uz",
    tag: "ai",
    hue: "#00d4ff",
    flagship: true,
    case: true,
    metric: { n: "24", label: { en: "sources, unattended", uz: "manba, qarovsiz", ru: "источника, без няньки", zh: "个信源，无人值守" } },
    dek: {
      en: "Uzbek AI news wire. 24 sources, LLM summaries on a schedule, every item cites the original. Nobody in the loop.",
      uz: "O‘zbekcha AI yangiliklar lentasi. 24 manba, jadval bo‘yicha LLM xulosalari, har bir xabar manbaga havola qiladi. Jarayonda odam yo‘q.",
      ru: "Узбекская AI-новостная лента. 24 источника, LLM-сводки по расписанию, каждая заметка ссылается на оригинал. Человека в цикле нет.",
      zh: "乌兹别克语 AI 新闻流。24 个信源，按计划生成 LLM 摘要，每条都标注原文出处。流程里没有人。"
    },
    stack: ["Claude API", "Cron", "RSS", "Telegram"],
    story: {
      problem: {
        en: "Uzbek AI news is either a Russian translation with the names left in, or nothing. People who want a wire in their own language get a Facebook dump.",
        uz: "O‘zbekcha AI yangiliklari yo ismlari tarjima qilinmagan ruscha ko‘chirma, yo umuman yo‘q. O‘z tilida lenta istaganlar Facebook uyumini oladi.",
        ru: "Узбекские AI-новости — это либо перевод с русского с непереведёнными именами, либо ничего. Кто хочет ленту на своём языке, получает свалку из Facebook.",
        zh: "乌兹别克语的 AI 新闻，要么是连人名都没译的俄语转写，要么干脆没有。想用母语看新闻流的人，只能去翻 Facebook。"
      },
      constraint: {
        en: "I cannot sit on a news desk. It has to publish while I am on a balcony with a grinder in my hand.",
        uz: "Men tahririyatda o‘tira olmayman. U men qo‘limda bolgarka bilan balkonda turganimda ham chiqishi kerak.",
        ru: "Я не могу сидеть в редакции. Лента должна выходить, пока я на балконе с болгаркой в руках.",
        zh: "我没法坐在编辑部里。我手里拿着角磨机站在阳台上的时候，它也得照常发布。"
      },
      shipped: {
        en: "24 sources. Scheduled LLM summaries. Every item linked to the original. RSS and Telegram. Nobody in the loop once the pipeline is up.",
        uz: "24 manba. Jadval bo‘yicha LLM xulosalari. Har bir xabar asl manbaga bog‘langan. RSS va Telegram. Quvur ishga tushgach, jarayonda odam qolmaydi.",
        ru: "24 источника. LLM-сводки по расписанию. Каждая заметка со ссылкой на оригинал. RSS и Telegram. После запуска пайплайна человека в цикле нет.",
        zh: "24 个信源。按计划生成的 LLM 摘要。每一条都链回原文。RSS 和 Telegram。管道跑起来之后，流程里就没有人了。"
      },
      hard: {
        en: "Uzbek LLM quality. A summary that invents a source is worse than silence. The link back to the original is the load-bearing wall.",
        uz: "O‘zbek tilida LLM sifati. Manbani o‘ylab topgan xulosa sukutdan yomonroq. Asl manbaga havola — bu yuk ko‘taruvchi devor.",
        ru: "Качество LLM на узбекском. Сводка, выдумавшая источник, хуже молчания. Ссылка на оригинал — несущая стена.",
        zh: "乌兹别克语的大模型质量。一条编造出处的摘要，比沉默更糟。回到原文的那个链接，是承重墙。"
      },
    },
  },
  {
    slug: "chertma",
    name: "Chertma",
    domain: "chertma.maqsudjon.com",
    url: "https://chertma.maqsudjon.com",
    tag: "ai",
    hue: "#00ff88",
    flagship: true,
    case: true,
    metric: { n: "4.89M", label: { en: "word forms, open", uz: "so‘z shakli, ochiq", ru: "словоформ, открыто", zh: "个词形，开放数据" } },
    // Chertma shows itself working: the ASCII a keyboard can type, corrected
    // in place to the New Latin it should have been.
    demo: { from: "to'g'ri o'zbekcha", to: "to‘g‘ri o‘zbekcha", label: "ascii → ş ç ö ğ" },
    dek: {
      en: "Type ASCII, get correct Uzbek New Latin — ş ç ö ğ. Offline. An open 28-million-row lexicon underneath.",
      uz: "ASCII yozing — to‘g‘ri o‘zbek yangi lotinini oling: ş ç ö ğ. Oflayn. Ostida 28 million qatorli ochiq leksikon.",
      ru: "Печатаешь ASCII — получаешь правильную узбекскую новую латиницу: ş ç ö ğ. Офлайн. Под ним открытый лексикон на 28 млн строк.",
      zh: "敲 ASCII，得到正确的乌兹别克新拉丁字母 —— ş ç ö ğ。离线可用。底下垫着一个 2800 万行的开放词库。"
    },
    stack: ["Vanilla JS", "Telegram bot", "Hugging Face"],
    links: [
      { label: "@Chertmabot", url: "https://t.me/chertmabot" },
      { label: "uz-lexicon-skeleton", url: "https://huggingface.co/datasets/Maqsudjonpolatov/uz-lexicon-skeleton" },
    ],
    story: {
      problem: {
        en: "Uzbek New Latin (ş ç ö ğ) is a pain on a normal keyboard. People skip the marks. Search breaks. Keyboards pretend the language is ASCII.",
        uz: "Oddiy klaviaturada o‘zbek yangi lotini (ş ç ö ğ) azob. Odamlar belgilarni tashlab ketadi. Qidiruv buziladi. Klaviaturalar tilni ASCII deb o‘ylaydi.",
        ru: "Узбекская новая латиница (ş ç ö ğ) на обычной клавиатуре — мучение. Люди пропускают знаки. Поиск ломается. Клавиатуры делают вид, что язык — это ASCII.",
        zh: "乌兹别克新拉丁字母（ş ç ö ğ）在普通键盘上很难打。大家索性不打附加符号，搜索就此失灵。键盘假装这门语言就是 ASCII。"
      },
      constraint: {
        en: "Keyboard in, marks out. No install, no account, works with the plane in airplane mode.",
        uz: "Klaviaturadan kiradi, belgilar bilan chiqadi. O‘rnatish yo‘q, akkaunt yo‘q, samolyot rejimida ham ishlaydi.",
        ru: "Вошло с клавиатуры — вышло со знаками. Без установки, без аккаунта, работает в авиарежиме.",
        zh: "键盘输进去，符号出来。不用安装，不用账号，飞行模式下也能用。"
      },
      shipped: {
        en: "A converter, a Telegram bot, and a dataset: 4.89M word forms, 23.2M bigrams, a skeleton index for keyboard-indistinguishable forms. CC BY 4.0. The dataset feeds the tool.",
        uz: "Konvertor, Telegram bot va dataset: 4,89 mln so‘z shakli, 23,2 mln bigramma, klaviaturada farqlanmaydigan shakllar uchun skelet indeks. CC BY 4.0. Dataset vositani oziqlantiradi.",
        ru: "Конвертер, Telegram-бот и датасет: 4,89 млн словоформ, 23,2 млн биграмм, скелет-индекс для неразличимых на клавиатуре форм. CC BY 4.0. Датасет кормит инструмент.",
        zh: "一个转换器、一个 Telegram 机器人，以及一个数据集：489 万个词形、2320 万个二元组，外加一份针对键盘上无法区分的形式的骨架索引。CC BY 4.0。数据集喂养着这个工具。"
      },
      hard: {
        en: "Keyboard-indistinguishable forms. The skeleton index is the product. The bot is only the door.",
        uz: "Klaviaturada farqlanmaydigan shakllar. Asl mahsulot — skelet indeks. Bot faqat eshik.",
        ru: "Формы, неразличимые на клавиатуре. Продукт — это скелет-индекс. Бот только дверь.",
        zh: "键盘上无法区分的那些形式。真正的产品是骨架索引，机器人只是门。"
      },
    },
  },
  {
    slug: "nullsample",
    name: "Nullsample",
    domain: "nullsample.maqsudjon.com",
    url: "https://nullsample.maqsudjon.com",
    tag: "music",
    hue: "#c084fc",
    case: true,
    metric: { n: "6", label: { en: "stems, zero samples", uz: "stem, nol sempl", ru: "стема, ноль сэмплов", zh: "条音轨，零采样" } },
    dek: {
      en: "Music from code. Zero samples, six stems, same seed = same track. Source public.",
      uz: "Koddan musiqa. Nol sempl, olti stem, bir xil seed = bir xil trek. Manba ochiq.",
      ru: "Музыка из кода. Ноль сэмплов, шесть стемов, тот же seed = тот же трек. Исходник открыт.",
      zh: "用代码做音乐。零采样，六条音轨，同一个 seed 得到同一首曲子。源码公开。"
    },
    stack: ["Web Audio", "AGPL-3.0"],
    story: {
      problem: {
        en: "Most ‘generative music’ is a sample pack with a seed on top. You cannot hear how it was made, and you cannot make it again.",
        uz: "Ko‘pchilik ‘generativ musiqa’ — ustiga seed qo‘yilgan sempl to‘plami. Qanday yasalganini eshitib bo‘lmaydi, qaytadan yasab ham bo‘lmaydi.",
        ru: "Большинство «генеративной музыки» — это сэмпл-пак с seed сверху. Не слышно, как это сделано, и повторить нельзя.",
        zh: "大多数「生成音乐」不过是加了个 seed 的采样包。你听不出它是怎么做出来的，也没法再做一遍。"
      },
      constraint: {
        en: "Zero samples. Seed-reproducible. In the browser. Source public.",
        uz: "Nol sempl. Seed bo‘yicha qayta takrorlanadi. Brauzerda. Manba ochiq.",
        ru: "Ноль сэмплов. Воспроизводимо по seed. В браузере. Исходник открыт.",
        zh: "零采样。由 seed 决定，可复现。在浏览器里跑。源码公开。"
      },
      shipped: {
        en: "Six stems. Web Audio. Same seed, same track, every time. AGPL-3.0 — the code is the instrument.",
        uz: "Olti stem. Web Audio. Bir xil seed — har safar bir xil trek. AGPL-3.0 — kodning o‘zi asbob.",
        ru: "Шесть стемов. Web Audio. Тот же seed — тот же трек, каждый раз. AGPL-3.0 — код и есть инструмент.",
        zh: "六条音轨。Web Audio。同一个 seed，每次都是同一首曲子。AGPL-3.0 —— 代码本身就是乐器。"
      },
      hard: {
        en: "Seed-deterministic audio that still sounds like a track, not a demo of Math.random().",
        uz: "Seedga bog‘liq deterministik audio, lekin baribir trekdek yangraydi — Math.random() demosi emas.",
        ru: "Детерминированное по seed аудио, которое всё-таки звучит как трек, а не как демо Math.random().",
        zh: "由 seed 决定的音频，还要听起来像一首曲子，而不是 Math.random() 的演示。"
      },
    },
  },
  {
    slug: "tadam",
    name: "Tadam",
    domain: "tadam.uz",
    url: "https://tadam.uz",
    tag: "tools",
    hue: "#ffb347",
    case: true,
    metric: { n: "1", label: { en: "QR, no app", uz: "QR, ilovasiz", ru: "QR, без приложения", zh: "个二维码，免安装" } },
    dek: {
      en: "Wedding photos in one album. One QR, no app, no signup. Used at a real wedding the week it shipped.",
      uz: "To‘y suratlari bitta albomda. Bitta QR, ilova yo‘q, ro‘yxatdan o‘tish yo‘q. Chiqqan haftasidayoq haqiqiy to‘yda ishlatildi.",
      ru: "Свадебные фото в одном альбоме. Один QR, без приложения, без регистрации. На настоящей свадьбе в неделю запуска.",
      zh: "婚礼照片汇进同一个相册。一个二维码，不用装 App，不用注册。上线那一周就用在了真正的婚礼上。"
    },
    stack: ["Cloudflare Workers", "R2", "No signup"],
    story: {
      problem: {
        en: "A wedding produces a thousand photos on a hundred cameras. Someone makes a WhatsApp group. The album dies in six threads.",
        uz: "Bitta to‘y yuzta kamerada mingta surat qoldiradi. Kimdir WhatsApp guruh ochadi. Albom olti xil chatda yo‘qoladi.",
        ru: "Свадьба — это тысяча фото на сотне камер. Кто-то создаёт группу в WhatsApp. Альбом умирает в шести переписках.",
        zh: "一场婚礼会在一百台相机里留下一千张照片。有人建了个 WhatsApp 群，相册就死在六个聊天窗口里。"
      },
      constraint: {
        en: "No app store. No signup. No database bill. One QR on the table, because that is what a guest will actually scan.",
        uz: "App Store yo‘q. Ro‘yxatdan o‘tish yo‘q. Baza uchun hisob yo‘q. Stol ustida bitta QR — mehmon aynan shuni skanerlaydi.",
        ru: "Никакого стора. Никакой регистрации. Никакого счёта за базу. Один QR на столе — именно его гость и правда отсканирует.",
        zh: "不上应用商店。不注册。不付数据库账单。桌上一个二维码，因为客人真正会扫的就是它。"
      },
      shipped: {
        en: "Guests drop photos into one album. Export the whole thing as one file. Used at a real wedding the week it shipped.",
        uz: "Mehmonlar suratlarni bitta albomga tashlaydi. Hammasini bitta fayl qilib yuklab olasiz. Chiqqan haftasida haqiqiy to‘yda ishlatildi.",
        ru: "Гости скидывают фото в один альбом. Выгрузка — одним файлом. На настоящей свадьбе в неделю запуска.",
        zh: "客人把照片丢进同一个相册，整本可以导出成一个文件。上线那一周就用在了真正的婚礼上。"
      },
      hard: {
        en: "A no-app photo album that does not become a graveyard of accounts. If the guest has to install something, you already lost.",
        uz: "Ilovasiz albom, lekin akkauntlar qabristoniga aylanmasligi kerak. Mehmon biror narsa o‘rnatishi kerak bo‘lsa, siz allaqachon yutqazgansiz.",
        ru: "Альбом без приложения, который не превращается в кладбище аккаунтов. Если гостю надо что-то установить — вы уже проиграли.",
        zh: "一个不用装 App 的相册，还不能变成账号的坟场。只要客人得先安装点什么，你就已经输了。"
      },
    },
  },
  {
    slug: "kvadrat",
    name: "KVADRAT",
    domain: "kvdrt.maqsudjon.com",
    url: "https://kvdrt.maqsudjon.com",
    tag: "steel",
    hue: "#7dd3fc",
    case: true,
    metric: { n: "m²", label: { en: "priced on site", uz: "obyektda hisoblanadi", ru: "считается на объекте", zh: "现场就能报价" } },
    dek: {
      en: "m² calculator for window grilles. Free-text Uzbek and Russian. Offline, PDF out. Built for the shop I work in.",
      uz: "Panjaralar uchun m² hisoblagich. O‘zbekcha va ruscha erkin matn. Oflayn, PDF chiqaradi. O‘zim ishlaydigan ustaxona uchun qilingan.",
      ru: "Калькулятор m² для оконных решёток. Свободный текст на узбекском и русском. Офлайн, вывод в PDF. Сделан для цеха, где я работаю.",
      zh: "防盗窗的平方米计算器。乌兹别克语和俄语自由文本输入。离线可用，导出 PDF。为我自己干活的那家车间做的。"
    },
    stack: ["Free-text parser", "PDF", "Offline"],
    story: {
      problem: {
        en: "Welders price window grilles on paper, then argue about square metres on site. The calculator on the phone is a notes app and a guess.",
        uz: "Payvandchilar panjara narxini qog‘ozda hisoblaydi, keyin obyektda kvadrat metr ustida tortishadi. Telefondagi ‘hisoblagich’ — bu bloknot va taxmin.",
        ru: "Сварщики считают решётки на бумаге, потом спорят о квадратных метрах на объекте. «Калькулятор» в телефоне — это заметки и догадка.",
        zh: "焊工在纸上算防盗窗的价，然后在现场为平方米争执。手机上那个「计算器」其实是备忘录加猜测。"
      },
      constraint: {
        en: "Offline. Dusty phones. Uzbek and Russian free text. Built for people who were doing this on paper — including me.",
        uz: "Oflayn. Changli telefonlar. O‘zbekcha va ruscha erkin matn. Buni qog‘ozda qilib yurganlar uchun — shu jumladan o‘zim uchun.",
        ru: "Офлайн. Пыльные телефоны. Свободный текст на узбекском и русском. Для тех, кто делал это на бумаге — включая меня.",
        zh: "离线。满是灰的手机。乌兹别克语和俄语自由文本。给那些一直在纸上算的人做的 —— 包括我自己。"
      },
      shipped: {
        en: "Type the opening, get the m² and a PDF quote. Used on actual jobs, not as a portfolio toy.",
        uz: "O‘lchamni yozasiz — m² va PDF hisob-kitob chiqadi. Portfolio o‘yinchog‘i emas, haqiqiy buyurtmalarda ishlatiladi.",
        ru: "Вводишь проём — получаешь m² и PDF-смету. Используется на реальных заказах, а не как игрушка для портфолио.",
        zh: "输入开口尺寸，得到平方米和一份 PDF 报价。用在真实订单上，不是作品集里的玩具。"
      },
      hard: {
        en: "Parsing “2.1 ga 1.4, 6 dona, tepa 15” into a quote without a form wizard the shop will never fill in.",
        uz: "“2.1 ga 1.4, 6 dona, tepa 15” ni hisob-kitobga aylantirish — ustaxona hech qachon to‘ldirmaydigan forma sehrgarisiz.",
        ru: "Разобрать «2.1 ga 1.4, 6 dona, tepa 15» в смету — без мастера форм, который в цеху никто не заполнит.",
        zh: "把「2.1 ga 1.4, 6 dona, tepa 15」解析成一份报价，而且不能靠一个车间永远不会填的表单向导。"
      },
    },
  },
  {
    slug: "davomat",
    name: "Davomat",
    domain: "davomat.maqsudjon-polatov.workers.dev",
    url: "https://davomat.maqsudjon-polatov.workers.dev",
    tag: "education",
    hue: "#2dd4bf",
    beta: true,
    dek: {
      en: "Attendance for university group monitors, inside Telegram. 25 students marked in under a minute, offline-safe.",
      uz: "Guruh sardorlari uchun yo‘qlama — Telegram ichida. 25 talaba bir daqiqadan kam vaqtda, oflaynda ham ishlaydi.",
      ru: "Посещаемость для старост, прямо в Telegram. 25 студентов меньше чем за минуту, работает офлайн.",
      zh: "给大学班长用的考勤，直接跑在 Telegram 里。25 名学生一分钟内点完，断网也能用。"
    },
  },
  {
    slug: "chzq",
    name: "Chiziq / CHZQ",
    domain: "chzq.uz",
    url: "https://chzq.uz",
    tag: "studio",
    hue: "#22d3ee",
    dek: {
      en: "Productised web studio: fixed scopes, fixed prices, live portfolio in an iframe instead of screenshots.",
      uz: "Mahsulotlashtirilgan veb-studiya: aniq hajm, aniq narx, skrinshot emas — iframe’dagi jonli portfolio.",
      ru: "Продуктизированная веб-студия: фиксированный объём, фиксированная цена, живое портфолио в iframe вместо скриншотов.",
      zh: "产品化的网页工作室：固定范围、固定价格，作品集用 iframe 直接跑真站点，而不是截图。"
    },
  },
  {
    slug: "pierics",
    name: "Pierics",
    domain: "pierics.com",
    url: "https://pierics.com",
    tag: "education",
    hue: "#fb7185",
    dek: {
      en: "Daily IELTS vocabulary game. One round a day, no account.",
      uz: "Har kunlik IELTS lug‘at o‘yini. Kuniga bitta raund, akkauntsiz.",
      ru: "Ежедневная игра на лексику IELTS. Один раунд в день, без аккаунта.",
      zh: "每天一局的 IELTS 词汇游戏。一天一轮，不用账号。"
    },
  },
  {
    slug: "minnos",
    name: "Minnos",
    domain: "minnos.cc",
    url: "https://minnos.cc",
    tag: "education",
    hue: "#fbbf24",
    dek: {
      en: "26 English cat idioms, with audio, explained in Uzbek.",
      uz: "26 ta inglizcha mushuk iborasi — audio bilan, o‘zbekcha izohlangan.",
      ru: "26 английских «кошачьих» идиом с аудио, с объяснением на узбекском.",
      zh: "26 个和猫有关的英语习语，配音频，用乌兹别克语讲解。"
    },
  },
  {
    slug: "zedavlod",
    name: "ZED AVLOD School",
    domain: "zedavlod.uz",
    url: "https://zedavlod.uz",
    tag: "client",
    hue: "#34d399",
    dek: {
      en: "Language school in To‘raqo‘rg‘on. English, IELTS, CEFR, Ibrat, DTM. Real results, no invented ones.",
      uz: "To‘raqo‘rg‘ondagi til markazi. Ingliz tili, IELTS, CEFR, Ibrat, DTM. Natijalar haqiqiy, o‘ylab topilgani yo‘q.",
      ru: "Языковая школа в Тюракургане. Английский, IELTS, CEFR, Ibrat, DTM. Результаты настоящие, выдуманных нет.",
      zh: "托拉库尔干的语言学校。英语、IELTS、CEFR、Ibrat、DTM。成绩是真实的，没有编造。"
    },
  },
  {
    slug: "ctnlc",
    name: "CTN Language Centre",
    domain: "ctnlc.uz",
    url: "https://ctnlc.uz",
    tag: "client",
    hue: "#60a5fa",
    dek: {
      en: "Tashkent language centre. A1–C1, IELTS intensive, kids, speaking club. Trilingual, one file.",
      uz: "Toshkentdagi til markazi. A1–C1, IELTS intensiv, bolalar, speaking klub. Uch tilli, bitta fayl.",
      ru: "Языковой центр в Ташкенте. A1–C1, интенсив IELTS, дети, speaking club. Три языка, один файл.",
      zh: "塔什干的语言中心。A1–C1、IELTS 强化、少儿班、口语俱乐部。三种语言，一个文件。"
    },
  },
  {
    slug: "payvandchi",
    name: "Payvandchi",
    domain: "payvandchi.maqsudjon.com",
    url: "https://payvandchi.maqsudjon.com",
    tag: "steel",
    hue: "#f97316",
    dek: {
      en: "Catalogue for the metal workshop. Grilles, railings, canopies — photographed on the job, not staged.",
      uz: "Temirchilik ustaxonasi katalogi. Panjara, panjaralik, soyabon — obyektda suratga olingan, sahnalashtirilmagan.",
      ru: "Каталог металлоцеха. Решётки, перила, навесы — сняты на объекте, не постановочно.",
      zh: "金属车间的作品目录。防盗窗、栏杆、雨棚 —— 都是在施工现场拍的，没有摆拍。"
    },
  },
  {
    slug: "reshotkachi",
    name: "Reshotkachi",
    domain: "reshotkachi.maqsudjon.com",
    url: "https://reshotkachi.maqsudjon.com",
    tag: "steel",
    hue: "#94a3b8",
    dek: {
      en: "Second grille catalogue, Russian-first, built as a 3D wall of 123 real photos.",
      uz: "Ikkinchi panjara katalogi, ruschaga mo‘ljallangan, 123 ta haqiqiy surat 3D devor sifatida.",
      ru: "Второй каталог решёток, по-русски, собран как 3D-стена из 123 настоящих фото.",
      zh: "第二本防盗窗目录，以俄语为主，做成了 123 张真实照片的 3D 墙。"
    },
  },
  {
    slug: "maqsudjon",
    name: "maqsudjon.com",
    domain: "maqsudjon.com",
    url: "https://maqsudjon.com",
    tag: "lab",
    hue: "#e6edf3",
    dek: {
      en: "The lab and the build log. Long-form notes on every ship, in English and Uzbek.",
      uz: "Laboratoriya va build log. Har bir chiqarilgan ish haqida uzun yozuvlar — inglizcha va o‘zbekcha.",
      ru: "Лаборатория и build log. Длинные заметки по каждому релизу, на английском и узбекском.",
      zh: "实验室和构建日志。每一次发布都有长文记录，英语和乌兹别克语。"
    },
  },
];

export const posts = [
  {
    slug: "why-tou",
    date: "2026-09-19",
    title: {
      en: "Why a three-letter .gg",
      uz: "Nega uch harfli .gg",
      ru: "Почему трёхбуквенный .gg",
      zh: "为什么是三个字母的 .gg"
    },
    dek: {
      en: "maqsudjon.com stays the lab. tou.gg is the front door.",
      uz: "maqsudjon.com laboratoriya bo‘lib qoladi. tou.gg — kirish eshigi.",
      ru: "maqsudjon.com остаётся лабораторией. tou.gg — парадная дверь.",
      zh: "maqsudjon.com 仍然是实验室。tou.gg 是正门。"
    },
    body: {
      en: [
        "I already had a site. maqsudjon.com is the lab — the ASCII engine, the build log, the long name on the certificate. It is a good lab. It is a bad front door.",
        "I wanted a shape that does not pin the work to a country or to one product. Three letters and a neutral TLD do that. A course, a tool, a stream can all live under it, and the root still means the person.",
        "TOU is “to you.” The work is pointed at a student in Namangan, a welder pricing a grille, a guest at a wedding with a phone full of photos. Not at a category. Not at an “ecosystem.”",
        ".uz is home, and I will keep shipping .uz products. .gg is the handshake for everything else — lab.tou.gg, chat.tou.gg, whatever gets built next, without renaming the person every six months.",
        "pangea8 became FlareStamina because a product should be allowed to grow a real name. The umbrella should not have to. That is why this domain is three letters and a joke that is not a joke: shipped to you.",
      ],
      uz: [
        "Mening saytim allaqachon bor edi. maqsudjon.com — laboratoriya: ASCII dvigateli, build log, sertifikatdagi uzun ism. Laboratoriya sifatida yaxshi. Kirish eshigi sifatida yomon.",
        "Menga ishni na mamlakatga, na bitta mahsulotga bog‘lab qo‘ymaydigan shakl kerak edi. Uch harf va neytral domen zonasi shuni beradi. Kurs ham, vosita ham, striming ham shu ostida yashaydi, ildiz esa baribir odamni bildiradi.",
        "TOU — bu “to you”, ya’ni “sizga”. Ish Namangandagi talabaga, panjara narxini hisoblayotgan payvandchiga, telefoni to‘y suratlariga to‘lgan mehmonga qaratilgan. Kategoriyaga emas. “Ekotizim”ga emas.",
        ".uz — uy, va men .uz mahsulotlarini chiqaraveraman. .gg — qolgan hammasi uchun qo‘l berish: lab.tou.gg, chat.tou.gg, keyin nima qurilsa ham — har olti oyda odamning nomini o‘zgartirmasdan.",
        "pangea8 FlareStaminaga aylandi, chunki mahsulotga haqiqiy nom o‘sib chiqishga ruxsat berish kerak. Soyabonga esa shart emas. Shuning uchun bu domen uch harf va hazilga o‘xshagan rost: sizga yetkazildi.",
      ],
      ru: [
        "У меня уже был сайт. maqsudjon.com — это лаборатория: ASCII-движок, build log, длинное имя на сертификате. Как лаборатория — хорошо. Как парадная дверь — плохо.",
        "Мне нужна была форма, которая не привязывает работу ни к стране, ни к одному продукту. Три буквы и нейтральная зона это дают. Курс, инструмент, стрим — всё живёт под ней, а корень по-прежнему означает человека.",
        "TOU — это «to you», «вам». Работа направлена на студента в Намангане, на сварщика, который считает решётку, на гостя свадьбы с телефоном, полным фото. Не на категорию. Не на «экосистему».",
        ".uz — это дом, и я продолжу выпускать .uz-продукты. .gg — рукопожатие для всего остального: lab.tou.gg, chat.tou.gg, что угодно следующее — без переименования человека каждые полгода.",
        "pangea8 стал FlareStamina, потому что продукту нужно разрешать вырастить настоящее имя. Зонтику — не обязательно. Поэтому домен из трёх букв и шутка, которая не шутка: доставлено вам.",
      ],
      zh: [
        "我本来就有一个网站。maqsudjon.com 是实验室 —— ASCII 引擎、构建日志、证书上那个长长的名字。作为实验室它很好，作为正门它很糟。",
        "我需要一个既不把作品钉在某个国家、也不钉在某一个产品上的形状。三个字母加一个中性的顶级域名正好。课程、工具、直播都能住进来，而根域名指的仍然是这个人。",
        "TOU 就是 “to you”，给你。这些作品是给纳曼干的学生、给正在算防盗窗价钱的焊工、给手机里塞满婚礼照片的宾客的。不是给某个品类，也不是给什么「生态」。",
        ".uz 是家，我会继续发布 .uz 的产品。.gg 是给其余一切的握手 —— lab.tou.gg、chat.tou.gg，以后还会建什么都行，不必每半年把人重新改一次名。",
        "pangea8 变成了 FlareStamina，因为产品应该被允许长出一个真正的名字。伞不必如此。所以这个域名是三个字母，加上一句听起来像玩笑、却当真的话：已送达，给你。",
      ],
    },
  },
  {
    slug: "code-and-steel",
    date: "2026-09-19",
    title: {
      en: "Code and steel",
      uz: "Kod va temir",
      ru: "Код и сталь",
      zh: "代码与钢铁"
    },
    dek: {
      en: "The workshop is the engineering school. Measure, join, load-test the seam.",
      uz: "Ustaxona — muhandislik maktabi. O‘lchang, ulang, chokni yuk bilan sinang.",
      ru: "Цех — это инженерная школа. Замерь, соедини, нагрузи шов.",
      zh: "车间就是工程学校。量尺寸、拼接、给焊缝加载测试。"
    },
    body: {
      en: [
        "The shop is loud. Steel does not autocomplete. You measure the opening. You cut. You tack. You check the square. You run the seam. Then you hang your weight on it — or you do not ship it to a balcony on the fifth floor.",
        "That is the whole engineering loop. Software pretends the loop is optional, because the failure is a 500 and not a railing that lets go.",
        "I weld during the day in Tashkent. I specify for agents at night. The method is the same: write the joint, inspect the bead, load-test. If the agent hallucinated a library, that is a cold shut — grind it out, run it again.",
        "People treat the welding as a plot twist. It is the school. The useful diploma is the habit of not shipping a seam you would not stand on.",
      ],
      uz: [
        "Ustaxona shovqinli. Temirda avtoto‘ldirish yo‘q. O‘lchaysiz. Kesasiz. Nuqtalab ulaysiz. Burchakni tekshirasiz. Chokni yurgizasiz. Keyin unga o‘z vazningizni osasiz — yo beshinchi qavat balkoniga chiqarmaysiz.",
        "Muhandislik sikli — shundan iborat. Dasturiy ta’minot bu siklni ixtiyoriy deb ko‘rsatadi, chunki u yerdagi nosozlik — 500 xatosi, qo‘yib yuboradigan panjara emas.",
        "Kunduzi Toshkentda payvand qilaman. Kechqurun agentlarga spetsifikatsiya yozaman. Usul bir xil: chokni yozing, ulanishni tekshiring, yuk bilan sinang. Agent kutubxonani o‘ylab topgan bo‘lsa — bu ‘sovuq chok’: kesib tashlang va qaytadan yurgizing.",
        "Odamlar payvandchilikni kutilmagan burilish deb qabul qiladi. Aslida u maktab. Foydali diplom — o‘zing turolmaydigan chokni chiqarmaslik odati.",
      ],
      ru: [
        "В цеху шумно. У стали нет автодополнения. Ты замеряешь проём. Режешь. Прихватываешь. Проверяешь угол. Ведёшь шов. Потом виснешь на нём всем весом — или не отправляешь его на балкон пятого этажа.",
        "Это и есть весь инженерный цикл. Софт делает вид, что цикл необязателен, потому что отказ — это 500, а не перила, которые отпустили.",
        "Днём я варю в Ташкенте. Ночью пишу спецификации для агентов. Метод тот же: напиши шов, осмотри валик, нагрузи. Если агент выдумал библиотеку — это непровар: вырезать и пройти заново.",
        "Сварку воспринимают как сюжетный поворот. Это школа. Полезный диплом — привычка не сдавать шов, на котором сам не встанешь.",
      ],
      zh: [
        "车间很吵。钢材没有自动补全。你量开口，切割，点焊，检查直角，走满焊缝。然后把自己的体重挂上去 —— 不然就别把它送上五楼的阳台。",
        "这就是完整的工程循环。软件假装这个循环可有可无，因为那边的故障是一个 500，而不是一根松开的栏杆。",
        "白天我在塔什干焊接，夜里我为智能体写规格。方法是一样的：写接头、检查焊道、加载测试。智能体要是幻觉出一个不存在的库，那就是一处未熔合 —— 磨掉，重来。",
        "大家把焊工当成一个剧情反转。它其实是学校。真正有用的文凭，是不交付自己不敢站上去的焊缝这个习惯。",
      ],
    },
  },
];

/* Long-form archive, published on the lab. Titles are not translated: they are the titles. */
export const outbound = [
  { date: "2026-08-27", title: "Tadam: a wedding album with no app and no database", url: "https://maqsudjon.com/log/log-2026-08-27-tadam-wedding-photo-album.html" },
  { date: "2026-08-27", title: "Seven sites in six weeks", url: "https://maqsudjon.com/log/log-2026-08-27-seven-sites-six-weeks.html" },
  { date: "2026-08-24", title: "FlareStamina — login walls came down", url: "https://maqsudjon.com/log/log-2026-08-24-flarestamina-walls-hub-news-tools.html" },
  { date: "2026-08-22", title: "Rebuilt FlareStamina in a weekend, deleted the framework", url: "https://maqsudjon.com/log/log-2026-08-22-flarestamina-paper-redesign.html" },
  { date: "2026-08-07", title: "KVADRAT", url: "https://maqsudjon.com/log/log-2026-08-07-kvadrat-calculator.html" },
  { date: "2026-08-04", title: "Reshotkachi, second build", url: "https://maqsudjon.com/log/log-2026-08-04-reshotkachi-second-build.html" },
  { date: "2026-08-01", title: "Payvandchi workshop online", url: "https://maqsudjon.com/log/log-2026-08-01-payvandchi-workshop.html" },
  { date: "2026-07-25", title: "Chiziq web studio", url: "https://maqsudjon.com/log/log-2026-07-25-chiziq-web-studio.html" },
  { date: "2026-07-23", title: "Zed Avlod school", url: "https://maqsudjon.com/log/log-2026-07-23-zed-avlod-school.html" },
  { date: "2026-07-21", title: "CTN Language Centre", url: "https://maqsudjon.com/log/log-2026-07-21-ctn-language-centre.html" },
  { date: "2026-07-10", title: "pangea8 is now FlareStamina", url: "https://maqsudjon.com/log/log-2026-07-10-pangea8-is-now-flarestamina.html" },
];

export const languages = [
  {
    native: "O‘zbekcha", latin: { en: "Uzbek", uz: "O‘zbek", ru: "Узбекский", zh: "乌兹别克语" }, cefr: "C2", fill: 100, hue: "#00ff88",
    badge: { en: "Native", uz: "Ona tili", ru: "Родной", zh: "母语" },
    story: { en: "Working language of the LLM pipelines", uz: "LLM quvurlarining ish tili", ru: "Рабочий язык LLM-пайплайнов", zh: "LLM 管道的工作语言" },
    sample: "Mendan — sizga. Chertma imloni tuzatadi, shevani emas.",
  },
  {
    native: "English", latin: { en: "English", uz: "Ingliz", ru: "Английский", zh: "英语" }, cefr: "B2", fill: 72, hue: "#ff6b35",
    badge: { en: "IELTS 6.0", uz: "IELTS 6.0", ru: "IELTS 6.0", zh: "IELTS 6.0" },
    story: { en: "12 Aug 2026 · L6.0 · R5.0 · W5.5 · S6.5", uz: "2026-yil 12-avgust · L6.0 · R5.0 · W5.5 · S6.5", ru: "12 авг 2026 · L6.0 · R5.0 · W5.5 · S6.5", zh: "2026 年 8 月 12 日 · L6.0 · R5.0 · W5.5 · S6.5" },
    sample: "I weld metal by day. I ship software by night.",
  },
  {
    native: "한국어", latin: { en: "Korean", uz: "Koreys", ru: "Корейский", zh: "韩语" }, cefr: "A2", fill: 38, hue: "#ff4d8d",
    badge: { en: "TOPIK 2", uz: "TOPIK 2", ru: "TOPIK 2", zh: "TOPIK 2" },
    story: { en: "Certificate, 2023", uz: "Sertifikat, 2023", ru: "Сертификат, 2023", zh: "证书，2023 年" },
    sample: "안녕하세요. 타슈켄트에서 왔습니다.",
  },
  {
    native: "Русский", latin: { en: "Russian", uz: "Rus", ru: "Русский", zh: "俄语" }, cefr: "A2", fill: 25, hue: "#8b9cb3",
    badge: { en: "Receptive", uz: "Tushunaman", ru: "Пассивный", zh: "能读能听" },
    story: { en: "Workplace and reading", uz: "Ish joyida va o‘qishda", ru: "Работа и чтение", zh: "工作场合与阅读" },
    sample: "Понимаю. Говорю мало.",
  },
  {
    native: "中文", latin: { en: "Chinese", uz: "Xitoy", ru: "Китайский", zh: "中文" }, cefr: "A0", fill: 4, hue: "#ffb347", live: true,
    badge: { en: "Day", uz: "Kun", ru: "День", zh: "第" },
    badgeAfter: { en: "", uz: "", ru: "", zh: " 天" },
    story: { en: "Started 19 Sep 2026", uz: "2026-yil 19-sentabrda boshlandi", ru: "Начал 19 сен 2026", zh: "2026 年 9 月 19 日开始" },
    sample: "你好。我是马苏德。",
  },
];

export const cv = {
  summary: {
    en: "Independent product engineer. I direct AI coding agents end to end — spec, architecture, build, DNS and TLS, operations. Fifteen live sites in nineteen months while welding full-time in Tashkent. Flagship: FlareStamina, a free IELTS Academic platform with 144 tests in production.",
    uz: "Mustaqil mahsulot muhandisi. AI kod agentlarini boshdan oxirigacha boshqaraman — spetsifikatsiya, arxitektura, qurilish, DNS va TLS, ekspluatatsiya. Toshkentda to‘liq stavkada payvandchi bo‘lib ishlagan holda 19 oyda 15 ta jonli sayt. Asosiysi: FlareStamina — 144 ta testi prodda ishlayotgan bepul IELTS Academic platformasi.",
    ru: "Независимый продуктовый инженер. Веду AI-агентов от начала до конца — спецификация, архитектура, сборка, DNS и TLS, эксплуатация. Пятнадцать живых сайтов за девятнадцать месяцев, работая сварщиком на полную ставку в Ташкенте. Флагман: FlareStamina — бесплатная платформа IELTS Academic со 144 тестами в проде.",
    zh: "独立产品工程师。我把 AI 编码智能体从头带到尾 —— 规格、架构、构建、DNS 与 TLS、运维。在塔什干做全职焊工的同时，19 个月里上线了 15 个站点。旗舰产品：FlareStamina，一个生产环境里有 144 套试题的免费 IELTS Academic 平台。"
  },
  jobs: [
    {
      role: { en: "Independent product engineer", uz: "Mustaqil mahsulot muhandisi", ru: "Независимый продуктовый инженер", zh: "独立产品工程师" },
      org: { en: "tou.gg · Tashkent / remote", uz: "tou.gg · Toshkent / masofadan", ru: "tou.gg · Ташкент / удалённо", zh: "tou.gg · 塔什干 / 远程" },
      period: { en: "2025 — present", uz: "2025 — hozirgacha", ru: "2025 — настоящее время", zh: "2025 至今" },
      points: {
        en: [
          "Shipped 15 live sites in 19 months while welding full-time.",
          "Direct AI coding agents end to end: spec, architecture, build, DNS/TLS, operations.",
          "FlareStamina: 144 IELTS Academic tests in production, AI writing feedback, speaking lab. Most of it is free.",
          "AI Lenta: unattended Uzbek news wire, 24 sources, every item cites the original.",
          "Open-sourced uz-lexicon-skeleton (28,052,730 rows, CC BY 4.0) to back Chertma.",
        ],
        uz: [
          "To‘liq stavkada payvandchi bo‘lib ishlagan holda 19 oyda 15 ta jonli sayt chiqardim.",
          "AI kod agentlarini boshdan oxirigacha boshqaraman: spetsifikatsiya, arxitektura, qurilish, DNS/TLS, ekspluatatsiya.",
          "FlareStamina: prodda 144 ta IELTS Academic testi, AI yozma tahlili, speaking laboratoriyasi. Katta qismi bepul.",
          "AI Lenta: qarovsiz ishlaydigan o‘zbek yangiliklar lentasi, 24 manba, har bir xabar manbaga havola qiladi.",
          "Chertma ostida turadigan uz-lexicon-skeleton (28 052 730 qator, CC BY 4.0) ochiq kodga chiqarildi.",
        ],
        ru: [
          "Выпустил 15 живых сайтов за 19 месяцев, работая сварщиком на полную ставку.",
          "Веду AI-агентов от начала до конца: спецификация, архитектура, сборка, DNS/TLS, эксплуатация.",
          "FlareStamina: 144 теста IELTS Academic в проде, AI-фидбэк по письму, speaking-лаб. Большая часть бесплатна.",
          "AI Lenta: узбекская новостная лента без оператора, 24 источника, каждая заметка со ссылкой на оригинал.",
          "Выложил в открытый доступ uz-lexicon-skeleton (28 052 730 строк, CC BY 4.0) как основу Chertma.",
        ],
        zh: [
          "在塔什干做全职焊工的同时，19 个月里上线了 15 个站点。",
          "把 AI 编码智能体从头带到尾：规格、架构、构建、DNS/TLS、运维。",
          "FlareStamina：生产环境里 144 套 IELTS Academic 试题、AI 写作反馈、口语实验室。大部分免费。",
          "AI Lenta：无人值守的乌兹别克语新闻流，24 个信源，每条都标注原文出处。",
          "开源了 uz-lexicon-skeleton（28,052,730 行，CC BY 4.0）作为 Chertma 的底层。",
        ],
      },
    },
    {
      role: { en: "Metal fabricator", uz: "Payvandchi / temirchi", ru: "Сварщик по металлу", zh: "金属焊接工" },
      org: { en: "Workshop · Tashkent", uz: "Ustaxona · Toshkent", ru: "Цех · Ташкент", zh: "车间 · 塔什干" },
      period: { en: "2023 — present", uz: "2023 — hozirgacha", ru: "2023 — настоящее время", zh: "2023 至今" },
      points: {
        en: [
          "Design, fabricate and install window grilles, balcony railings and canopies.",
          "Built KVADRAT — an offline m² calculator used on actual jobs, not as a demo.",
        ],
        uz: [
          "Panjara, balkon panjaraligi va soyabonlarni loyihalash, yasash va o‘rnatish.",
          "KVADRAT yasadim — demo emas, haqiqiy buyurtmalarda ishlatiladigan oflayn m² hisoblagich.",
        ],
        ru: [
          "Проектирую, изготавливаю и монтирую решётки, балконные перила и навесы.",
          "Сделал KVADRAT — офлайн-калькулятор m², который используется на реальных заказах, а не как демо.",
        ],
        zh: [
          "设计、制作并安装防盗窗、阳台栏杆和雨棚。",
          "做了 KVADRAT —— 一个离线的平方米计算器，用在真实订单上，而不是演示。",
        ],
      },
    },
  ],
  education: [
    {
      title: { en: "BA English Philology", uz: "Ingliz filologiyasi (bakalavr)", ru: "Бакалавриат: английская филология", zh: "英语语文学 学士" },
      org: { en: "AIFU, Tashkent · 1st year, evening", uz: "AIFU, Toshkent · 1-kurs, kechki", ru: "AIFU, Ташкент · 1 курс, вечернее", zh: "AIFU，塔什干 · 一年级，夜校" },
      period: { en: "2026 —", uz: "2026 —", ru: "2026 —", zh: "2026 至今" },
    },
    {
      title: { en: "IELTS Academic 6.0", uz: "IELTS Academic 6.0", ru: "IELTS Academic 6.0", zh: "IELTS Academic 6.0" },
      org: { en: "CEFR B2 · L 6.0 · R 5.0 · W 5.5 · S 6.5", uz: "CEFR B2 · L 6.0 · R 5.0 · W 5.5 · S 6.5", ru: "CEFR B2 · L 6.0 · R 5.0 · W 5.5 · S 6.5", zh: "CEFR B2 · L 6.0 · R 5.0 · W 5.5 · S 6.5" },
      period: { en: "12 Aug 2026", uz: "12.08.2026", ru: "12 авг 2026", zh: "2026 年 8 月 12 日" },
    },
    {
      title: { en: "Electrician", uz: "Elektrik", ru: "Электрик", zh: "电工" },
      org: { en: "Diploma with honours", uz: "Qizil diplom", ru: "Красный диплом", zh: "优等毕业证书" },
      period: { en: "", uz: "", ru: "", zh: "" },
    },
    {
      title: { en: "Trucking", uz: "Trucking", ru: "Trucking", zh: "货运 Trucking" },
      org: { en: "MBA certificate, First Class", uz: "MBA sertifikati, First Class", ru: "Сертификат MBA, First Class", zh: "MBA 证书，一等" },
      period: { en: "", uz: "", ru: "", zh: "" },
    },
  ],
  stack: ["JS / TS", "Node", "Python", "Cloudflare Workers", "D1 / R2", "Firebase", "Supabase", "Claude API", "GitHub Actions", "Pages", "Web Audio", "Canvas"],
};

export const method = [
  { n: "01", label: { en: "Specify", uz: "Spetsifikatsiya", ru: "Спецификация", zh: "写规格" } },
  { n: "02", label: { en: "Direct the agents", uz: "Agentlarni boshqarish", ru: "Управление агентами", zh: "指挥智能体" } },
  { n: "03", label: { en: "Review", uz: "Tekshirish", ru: "Ревью", zh: "审查" } },
  { n: "04", label: { en: "Ship", uz: "Chiqarish", ru: "Релиз", zh: "发布" } },
  { n: "05", label: { en: "Operate", uz: "Yuritish", ru: "Эксплуатация", zh: "运维" } },
];
